server:
  port: 8081

kkrpc:
  zk:
    server: localhost:2181
    root: kkrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001

logging:
  level:
    root: error
    cn.kimmking.kkrpc: info