server:
  port: 8081

kkrpc:
  zk:
    server: localhost:2181
    root: kkrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 300
kkregistry:
  servers: http://localhost:8484

logging:
  level:
    root: error
    cn.kimmking.kkrpc: debug
    com.ctrip: debug

app:
  id: app1
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app1
    eagerLoad:
      enabled: false