apollo:
    autoUpdateInjectedSpringProperties: true
    bootstrap:
        eagerLoad:
            enabled: false
        enabled: true
        namespaces: app1
    cacheDir: /opt/data/
    cluster: default
    meta: http://kimmking.cn:8080
app:
    id: app1
kkregistry:
    enabled: true
    servers: http://localhost:8484
kkrpc:
    app:
        env: dev
        id: app1
        namespace: public
    provider:
        metas:
            dc: bj
            gray: false
            tc: 300
            unit: B001
    zk:
        root: kkrpc
        server: localhost:2181
logging:
    level:
        cn.kimmking.kkrpc: info
        com.ctrip: info
        root: error
server:
    port: 8081
